#!/bin/bash
set -eu

PATHS="$BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS"

echo "Sparse checking out the following paths: $PATHS"

git clone --filter=blob:none --sparse $BUILDKITE_REPO && cd "$(basename "$BUILDKITE_REPO" .git)"

for thisPath in $(echo $PATHS | cut -d ' ' -f 1-100); do
	echo Path: $thisPath; git sparse-checkout set $thisPath
done

buildkite-agent annotate "Sparse checkout of the following paths: $PATHS"
