#!/bin/bash
set -exu

echo "Working directory: $(pwd)"
echo "Sparse checking out the following paths: $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS"

# Clean build every time
cd ..
rm -rf $BUILDKITE_PIPELINE_NAME
git clone --no-checkout $BUILDKITE_REPO $BUILDKITE_PIPELINE_NAME && cd $BUILDKITE_PIPELINE_NAME
git sparse-checkout init --cone

# Always checkout the .buildkite
git sparse-checkout set .buildkite $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS
buildkite-agent annotate "Sparse checkout of the following paths: $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS"
