#!/bin/bash
set -eu

# Add github key if not already in known_hosts, otherwise clone will hang
GITHUB_KEY=$(ssh-keyscan -H github.com)
grep -qxF "$GITHUB_KEY" ~/.ssh/known_hosts || echo "$GITHUB_KEY" >> ~/.ssh/known_hosts

echo "Working directory: $(pwd)"
echo "Sparse checking out the following paths: $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS"

# Clean build every time
cd ..
rm -rf $BUILDKITE_PIPELINE_NAME
git clone --no-checkout $BUILDKITE_REPO $BUILDKITE_PIPELINE_NAME && cd $BUILDKITE_PIPELINE_NAME
git sparse-checkout init --cone

# Always checkout the .buildkite
git sparse-checkout add .buildkite $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS
git checkout "$BUILDKITE_BRANCH"

buildkite-agent annotate "Sparse checkout of the following paths: $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATHS"
